FROM node:lts-alpine AS build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build --prod

FROM nginx


COPY --from=build /app/dist/docker-frontend-domo/browser /usr/share/nginx/html

